apiVersion: apps/v1
kind: Deployment
metadata:
  name: muchtodo-backend
  namespace: muchtodo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: muchtodo-backend
  template:
    metadata:
      labels:
        app: muchtodo-backend
    spec:
      containers:
        - name: backend
          image: muchtodo-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://admin:admin123@mongodb:27017/much_todo_db?authSource=admin"